version: "3"

vars:
  VERSION:
    sh: git rev-parse --short HEAD

env:
  BASE_APP_NAME: services-am-dataprep-api
  NAMESPACE: aftermath-services

  REGISTRY: ghcr.io/byvko-dev
  K8S_TYPE: deployment

tasks:
  build:
    desc: Build and tag the docker image. By default, image will bw pushed to remote repository, pass '-- load' to load image to local docker daemon.
    cmds:
      - docker buildx build --platform linux/amd64 -t $REGISTRY/$BASE_APP_NAME:{{.VERSION}} -t $REGISTRY/$BASE_APP_NAME:latest --{{.CLI_ARGS | default "push"}} --secret id=ssh_priv,src=$HOME/.ssh/id_rsa --secret id=ssh_pub,src=$HOME/.ssh/id_rsa.pub .

  restart:
    desc: Restart k8s deployment
    cmds:
      - kubectl rollout restart $K8S_TYPE/${SERVICE} -n ${NAMESPACE}
